apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    environment: prod
    version: v1
  name: api-gateway
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  type: ClusterIP
